
 //----------------------------------------------
 //
 //        Sketch Generated by Visuino
 //              www.visuino.com
 //          Version 7.8.3.60
 //
 //----------------------------------------------

#define VISUINO_ARDUINO_UNO

#include <OpenWire.h>
#include <Mitov.h>
#include <Wire.h>
#include <Mitov_Basic_I2C.h>
#include <Mitov_LiquidCrystalDisplay_I2C.h>

// Shared Component Member Variables

namespace ComponentVariables
{
class
{
public:
  uint32_t Value1 : 5;
  uint32_t Value2 : 2;

} BitFields;

class Variable1
{
public:
  inline static uint32_t GetValue() { return BitFields.Value1; }
  inline static void SetValue( uint32_t AValue ) { BitFields.Value1 = AValue; }

};
class Variable2
{
public:
  inline static uint32_t GetValue() { return BitFields.Value2; }
  inline static void SetValue( uint32_t AValue ) { BitFields.Value2 = AValue; }

};
} // ComponentVariables

// Arduino Constant Declarations

namespace VisuinoConstants
{
class TextValue1
{
public:
    inline static constexpr const char *GetValue() { return "----- * Mecatr\363nica * -----"; }
};

class TextValue0
{
public:
    inline static constexpr const char *GetValue() { return "------- Ingenier\355a --------"; }
};

} // VisuinoConstants

// Declarations

namespace Declarations
{
Mitov::LiquidCrystalDisplay<
  Mitov::LiquidCrystalDisplayI2C<
    TwoWire, // 0_TYPE_PIN
    Wire, // 1_NAME_PIN
    Mitov::ConstantProperty<2, uint8_t, 39 >, // Address
    Mitov::ConstantProperty<14, bool, false >, // AutoScroll
    Mitov::ConstantProperty<4, bool, true >, // Backlight
    Mitov::ConstantProperty<3, bool, true >, // BacklightPositive
    Mitov::ConstantProperty<17, bool, false >, // Blink
    Mitov::ConstantProperty<13, bool, true >, // Enabled
    Mitov::ConstantProperty<18, bool, false >, // Hight10Pixels
    Mitov::ConstantProperty<15, bool, false >, // RightToLeft
    Mitov::ConstantProperty<16, bool, false > // ShowCursor
    >, // 0_TYPE
  16, // Columns
  Mitov::TypedVariable<38, uint32_t, ::ComponentVariables::Variable2>, // FCursorLine
  Mitov::TypedVariable<32, uint32_t, ::ComponentVariables::Variable1>, // FCursorPos
  2 // Rows
   > _o_LiquidCrystalDisplay1;

Mitov::LiquidCrystalElementTextField<
    Mitov::LiquidCrystalDisplay<
      Mitov::LiquidCrystalDisplayI2C<
        TwoWire, // 0_TYPE_PIN
        Wire, // 1_NAME_PIN
        Mitov::ConstantProperty<2, uint8_t, 39 >, // Address
        Mitov::ConstantProperty<14, bool, false >, // AutoScroll
        Mitov::ConstantProperty<4, bool, true >, // Backlight
        Mitov::ConstantProperty<3, bool, true >, // BacklightPositive
        Mitov::ConstantProperty<17, bool, false >, // Blink
        Mitov::ConstantProperty<13, bool, true >, // Enabled
        Mitov::ConstantProperty<18, bool, false >, // Hight10Pixels
        Mitov::ConstantProperty<15, bool, false >, // RightToLeft
        Mitov::ConstantProperty<16, bool, false > // ShowCursor
        >, // 0_TYPE
      16, // Columns
      Mitov::TypedVariable<38, uint32_t, ::ComponentVariables::Variable2>, // FCursorLine
      Mitov::TypedVariable<32, uint32_t, ::ComponentVariables::Variable1>, // FCursorPos
      2 // Rows
       >, // 0_TYPE_OWNER
    Declarations::_o_LiquidCrystalDisplay1, // 1_NAME_OWNER
    Mitov::ConstantProperty<5, bool, true >, // AllignLeft
    Mitov::ConstantProperty<7, uint32_t, 0 >, // Column
    Mitov::ConstantProperty<6, char, ' ' >, // FillCharacter
    Mitov::ConstantPropertyString<3, ::VisuinoConstants::TextValue0 >, // InitialValue
    Mitov::ConstantProperty<8, uint32_t, 0 >, // Row
    Mitov::ConstantProperty<4, uint32_t, 16 > // Width
     > TArduinoLiquidCrystalElementTextField1;

Mitov::LiquidCrystalElementTextField<
    Mitov::LiquidCrystalDisplay<
      Mitov::LiquidCrystalDisplayI2C<
        TwoWire, // 0_TYPE_PIN
        Wire, // 1_NAME_PIN
        Mitov::ConstantProperty<2, uint8_t, 39 >, // Address
        Mitov::ConstantProperty<14, bool, false >, // AutoScroll
        Mitov::ConstantProperty<4, bool, true >, // Backlight
        Mitov::ConstantProperty<3, bool, true >, // BacklightPositive
        Mitov::ConstantProperty<17, bool, false >, // Blink
        Mitov::ConstantProperty<13, bool, true >, // Enabled
        Mitov::ConstantProperty<18, bool, false >, // Hight10Pixels
        Mitov::ConstantProperty<15, bool, false >, // RightToLeft
        Mitov::ConstantProperty<16, bool, false > // ShowCursor
        >, // 0_TYPE
      16, // Columns
      Mitov::TypedVariable<38, uint32_t, ::ComponentVariables::Variable2>, // FCursorLine
      Mitov::TypedVariable<32, uint32_t, ::ComponentVariables::Variable1>, // FCursorPos
      2 // Rows
       >, // 0_TYPE_OWNER
    Declarations::_o_LiquidCrystalDisplay1, // 1_NAME_OWNER
    Mitov::ConstantProperty<5, bool, true >, // AllignLeft
    Mitov::ConstantProperty<7, uint32_t, 3 >, // Column
    Mitov::ConstantProperty<6, char, ' ' >, // FillCharacter
    Mitov::ConstantPropertyString<3, ::VisuinoConstants::TextValue1 >, // InitialValue
    Mitov::ConstantProperty<8, uint32_t, 1 >, // Row
    Mitov::ConstantProperty<4, uint32_t, 16 > // Width
     > TArduinoLiquidCrystalElementTextField2;

} // Declarations

namespace ComponentsHardware
{
void SystemUpdateHardware()
{
}
} // ComponentsHardware

//The setup function is called once at startup of the sketch
void setup()
{
  Wire.begin();

  Declarations::_o_LiquidCrystalDisplay1.SystemInit();

  Declarations::TArduinoLiquidCrystalElementTextField1.SystemStart();
  Declarations::TArduinoLiquidCrystalElementTextField2.SystemStart();

  OpenWire::SystemStarted();
}

// The loop function is called in an endless loop
void loop()
{
}
